
#################################### 用户配置 开始#################################
#
oracle2es.latColumn: WD84
oracle2es.lonColumn: JD84

oracle2es.esUrl: http://10.192.19.161:9200/
oracle2es.maxThreadCount: 8
#统一索引类型
oracle2es.indexType: _doc
#统一索引DB名称，索引名为:tableName@dbName
oracle2es.indexDb: zhftyjjcpt

oracle2es.owner: ZHFTYJJCPT
#只读的表的列表，为空则读所有表。配置了只读（justRead）后，跳过（skip）逻辑失效。
oracle2es.justReadTB: XIAOFANG_YINHUAN,BJ0201,BJ0203
#需要跳过的库的列表，为空则不跳过。先判断只读，在判断是否跳过。当两个配置冲突时，参考只读，优先级更高。
oracle2es.skipReadTB: BJ0201

#################################### 用户配置 结束 ##########################################

server:
  port: 8080
#logging:
#  level:
#    root: INFO
spring:
  profiles:
    active: dev
  zipkin:
    base-url: http://10.192.19.162:18100
  service:
    name: ${spring.application.name}
  sleuth:
      #监控开关
      enabled: true
      #采样率
      sampler:
        percentage: 1
  output:
    ansi:
      enabled: detect
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  messages:
    basename: i18n/messages
    cache-seconds: -1
    encoding: utf-8
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@10.192.19.163:1521/orcl
    username: ZHFTYJJCPT
    password: ToKreDi*nJ

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate: INFO
  file: logs/db2es.log


